import type { Form } from '../../types';

export function buildGansidIndividualGroup(): Omit<Form, 'id' | 'status' | 'createdAt'> {
  const now = Date.now().toString();
  return {
    title: 'GANSID Congress 2026 Registration',
    description: 'October 23–25, 2026 · Hyderabad, India',
    thankYouMessage:
      'Thank you for registering for the GANSID Congress 2026! Your ticket is on its way to your email.',
    formType: 'event',
    settings: {
      groupPath: { enabled: true, maxSize: 5 },
      sendGuestConfirmationEmails: false,
      currency: 'USD',
      bogoEnabled: true,
    },
    fields: [
      { id: `f_${now}_mode`, type: 'registration-mode-selector',
        label: 'How are you registering?', required: true,
        groupEnabled: true, groupMaxSize: 5,
        individualLabel: 'Individual — just me',
        groupLabel: 'Group — up to 5 people' },
      { id: `f_${now}_fname`, type: 'text', label: 'First Name', required: true,
        placeholder: 'This will appear on your conference badge' },
      { id: `f_${now}_lname`, type: 'text', label: 'Last Name', required: true,
        placeholder: 'This will appear on your conference badge' },
      { id: `f_${now}_title`, type: 'select', label: 'Title', required: false,
        options: ['Mr.', 'Ms.', 'Mrs.', 'Dr.', 'Prof.'] },
      { id: `f_${now}_email`, type: 'email', label: 'Email Address', required: true },
      { id: `f_${now}_whatsapp`, type: 'phone', label: 'WhatsApp Number', required: false },
      { id: `f_${now}_org`, type: 'text', label: 'Institution/Organization', required: true },
      { id: `f_${now}_city`, type: 'text', label: 'City', required: false },
      { id: `f_${now}_country`, type: 'country', label: 'Country',
        required: true, usedForPricing: true },
      { id: `f_${now}_days`, type: 'checkbox',
        label: 'Which days will you be attending?', required: false,
        options: ['October 23, 2026', 'October 24, 2026', 'October 25, 2026'] },
      { id: `f_${now}_diet`, type: 'textarea', required: false,
        label: 'Do you have any dietary restrictions or allergies?' },
      { id: `f_${now}_access`, type: 'textarea', required: false,
        label: 'Do you have any accessibility needs?' },
      { id: `f_${now}_present`, type: 'radio', required: false,
        label: 'Will you be presenting at the Congress?',
        options: ['Yes, oral presentation', 'Yes, poster presentation',
          'No, I will not be presenting', 'I am unsure if I will be presenting'] },
      { id: `f_${now}_emerg_name`, type: 'text', label: 'Emergency contact name', required: false },
      { id: `f_${now}_emerg_phone`, type: 'phone', label: 'Emergency contact phone number', required: false },
      { id: `f_${now}_emerg_rel`, type: 'text', label: 'Relationship of emergency contact to yourself', required: false },
      { id: `f_${now}_consent_list`, type: 'radio', required: false,
        label: 'Do you want to be on the list of attendees that may appear on our website or social media?',
        options: ['Yes', 'No'] },
      { id: `f_${now}_consent_photo`, type: 'boolean', required: true,
        label: 'I understand that photos or videos may be taken at the event for GANSID promotional purposes.' },
      { id: `f_${now}_consent_promo`, type: 'radio', required: false,
        label: 'Do you consent to receiving promotional materials regarding the GANSID and the Congress by email?',
        options: ['Yes', 'No'] },
      { id: `f_${now}_consent_conduct`, type: 'boolean', required: true,
        label: 'I have read and agree to the Code of Conduct' },
      { id: `f_${now}_consent_terms`, type: 'boolean', required: true,
        label: 'I have read and agree to the Terms & Conditions' },
      { id: `f_${now}_consent_liability`, type: 'boolean', required: true,
        label: 'I have read and agree to the Disclaimer & Liability waiver' },
      { id: `f_${now}_ticket`, type: 'ticket', label: 'Registration', required: false,
        ticketConfig: { currency: 'USD', items: [], promoCodes: [] } },
    ] as any,
  } as any;
}
